Repository googleapis/nodejs-gce-images, pull requests merged in 2020-07, with the labels that each got.

#245 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#246 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#250 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#249 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#253 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#254 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#255 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#256 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#257 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#258 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
